steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/ashisha2307/kroger-app-test"]
    env: ["PROJECT_ROOT=github.com/ashisha2307/kroger-app-test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/kroger-mobia-test/kroger-app-test:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/kroger-mobia-test/kroger-app-test:$REVISION_ID"
