steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/ashisha2307/kroger-app-test"]
    env: ["PROJECT_ROOT=github.com/ashisha2307/kroger-app-test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us.gcr.io/kr-73xqrdk-sandbox-de/kroger-app-test:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "us.gcr.io/kr-73xqrdk-sandbox-de/kroger-app-test:$REVISION_ID"
